/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTrocarSenhaRouteImport } from './routes/_authenticated/trocar-senha'
import { Route as AuthenticatedPendenciasRouteImport } from './routes/_authenticated/pendencias'
import { Route as AuthenticatedPedagogicoRouteImport } from './routes/_authenticated/pedagogico'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCaptacaoRouteImport } from './routes/_authenticated/captacao'
import { Route as AuthenticatedBaseConhecimentoRouteImport } from './routes/_authenticated/base-conhecimento'
import { Route as AuthenticatedAdministrativoRouteImport } from './routes/_authenticated/administrativo'
import { Route as AuthenticatedPedagogicoIndexRouteImport } from './routes/_authenticated/pedagogico.index'
import { Route as AuthenticatedFinanceiroIndexRouteImport } from './routes/_authenticated/financeiro.index'
import { Route as AuthenticatedConfiguracoesIndexRouteImport } from './routes/_authenticated/configuracoes.index'
import { Route as AuthenticatedAdministrativoIndexRouteImport } from './routes/_authenticated/administrativo.index'
import { Route as AuthenticatedFinanceiroOrcamentoRouteImport } from './routes/_authenticated/financeiro.orcamento'
import { Route as AuthenticatedFinanceiroFornecedoresRouteImport } from './routes/_authenticated/financeiro.fornecedores'
import { Route as AuthenticatedFinanceiroDespesasRouteImport } from './routes/_authenticated/financeiro.despesas'
import { Route as AuthenticatedConfiguracoesUsuariosRouteImport } from './routes/_authenticated/configuracoes.usuarios'
import { Route as AuthenticatedAdministrativoQualificacaoRouteImport } from './routes/_authenticated/administrativo.qualificacao'
import { Route as AuthenticatedAdministrativoMateriaisRouteImport } from './routes/_authenticated/administrativo.materiais'
import { Route as AuthenticatedAdministrativoBeneficiosRouteImport } from './routes/_authenticated/administrativo.beneficios'
import { Route as AuthenticatedPedagogicoTurmasIdRouteImport } from './routes/_authenticated/pedagogico.turmas.$id'
import { Route as AuthenticatedPedagogicoTurmasIdIndexRouteImport } from './routes/_authenticated/pedagogico.turmas.$id.index'
import { Route as AuthenticatedPedagogicoTurmasIdFrequenciaRouteImport } from './routes/_authenticated/pedagogico.turmas.$id.frequencia'
import { Route as AuthenticatedPedagogicoTurmasIdCursistasRouteImport } from './routes/_authenticated/pedagogico.turmas.$id.cursistas'
import { Route as AuthenticatedPedagogicoTurmasIdAulasRouteImport } from './routes/_authenticated/pedagogico.turmas.$id.aulas'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrocarSenhaRoute =
  AuthenticatedTrocarSenhaRouteImport.update({
    id: '/trocar-senha',
    path: '/trocar-senha',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPendenciasRoute = AuthenticatedPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedagogicoRoute = AuthenticatedPedagogicoRouteImport.update({
  id: '/pedagogico',
  path: '/pedagogico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaptacaoRoute = AuthenticatedCaptacaoRouteImport.update({
  id: '/captacao',
  path: '/captacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBaseConhecimentoRoute =
  AuthenticatedBaseConhecimentoRouteImport.update({
    id: '/base-conhecimento',
    path: '/base-conhecimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministrativoRoute =
  AuthenticatedAdministrativoRouteImport.update({
    id: '/administrativo',
    path: '/administrativo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedagogicoIndexRoute =
  AuthenticatedPedagogicoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPedagogicoRoute,
  } as any)
const AuthenticatedFinanceiroIndexRoute =
  AuthenticatedFinanceiroIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedConfiguracoesIndexRoute =
  AuthenticatedConfiguracoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedAdministrativoIndexRoute =
  AuthenticatedAdministrativoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdministrativoRoute,
  } as any)
const AuthenticatedFinanceiroOrcamentoRoute =
  AuthenticatedFinanceiroOrcamentoRouteImport.update({
    id: '/orcamento',
    path: '/orcamento',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroFornecedoresRoute =
  AuthenticatedFinanceiroFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroDespesasRoute =
  AuthenticatedFinanceiroDespesasRouteImport.update({
    id: '/despesas',
    path: '/despesas',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedConfiguracoesUsuariosRoute =
  AuthenticatedConfiguracoesUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedAdministrativoQualificacaoRoute =
  AuthenticatedAdministrativoQualificacaoRouteImport.update({
    id: '/qualificacao',
    path: '/qualificacao',
    getParentRoute: () => AuthenticatedAdministrativoRoute,
  } as any)
const AuthenticatedAdministrativoMateriaisRoute =
  AuthenticatedAdministrativoMateriaisRouteImport.update({
    id: '/materiais',
    path: '/materiais',
    getParentRoute: () => AuthenticatedAdministrativoRoute,
  } as any)
const AuthenticatedAdministrativoBeneficiosRoute =
  AuthenticatedAdministrativoBeneficiosRouteImport.update({
    id: '/beneficios',
    path: '/beneficios',
    getParentRoute: () => AuthenticatedAdministrativoRoute,
  } as any)
const AuthenticatedPedagogicoTurmasIdRoute =
  AuthenticatedPedagogicoTurmasIdRouteImport.update({
    id: '/turmas/$id',
    path: '/turmas/$id',
    getParentRoute: () => AuthenticatedPedagogicoRoute,
  } as any)
const AuthenticatedPedagogicoTurmasIdIndexRoute =
  AuthenticatedPedagogicoTurmasIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPedagogicoTurmasIdRoute,
  } as any)
const AuthenticatedPedagogicoTurmasIdFrequenciaRoute =
  AuthenticatedPedagogicoTurmasIdFrequenciaRouteImport.update({
    id: '/frequencia',
    path: '/frequencia',
    getParentRoute: () => AuthenticatedPedagogicoTurmasIdRoute,
  } as any)
const AuthenticatedPedagogicoTurmasIdCursistasRoute =
  AuthenticatedPedagogicoTurmasIdCursistasRouteImport.update({
    id: '/cursistas',
    path: '/cursistas',
    getParentRoute: () => AuthenticatedPedagogicoTurmasIdRoute,
  } as any)
const AuthenticatedPedagogicoTurmasIdAulasRoute =
  AuthenticatedPedagogicoTurmasIdAulasRouteImport.update({
    id: '/aulas',
    path: '/aulas',
    getParentRoute: () => AuthenticatedPedagogicoTurmasIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/administrativo': typeof AuthenticatedAdministrativoRouteWithChildren
  '/base-conhecimento': typeof AuthenticatedBaseConhecimentoRoute
  '/captacao': typeof AuthenticatedCaptacaoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/pedagogico': typeof AuthenticatedPedagogicoRouteWithChildren
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/administrativo/beneficios': typeof AuthenticatedAdministrativoBeneficiosRoute
  '/administrativo/materiais': typeof AuthenticatedAdministrativoMateriaisRoute
  '/administrativo/qualificacao': typeof AuthenticatedAdministrativoQualificacaoRoute
  '/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/financeiro/despesas': typeof AuthenticatedFinanceiroDespesasRoute
  '/financeiro/fornecedores': typeof AuthenticatedFinanceiroFornecedoresRoute
  '/financeiro/orcamento': typeof AuthenticatedFinanceiroOrcamentoRoute
  '/administrativo/': typeof AuthenticatedAdministrativoIndexRoute
  '/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/pedagogico/': typeof AuthenticatedPedagogicoIndexRoute
  '/pedagogico/turmas/$id': typeof AuthenticatedPedagogicoTurmasIdRouteWithChildren
  '/pedagogico/turmas/$id/aulas': typeof AuthenticatedPedagogicoTurmasIdAulasRoute
  '/pedagogico/turmas/$id/cursistas': typeof AuthenticatedPedagogicoTurmasIdCursistasRoute
  '/pedagogico/turmas/$id/frequencia': typeof AuthenticatedPedagogicoTurmasIdFrequenciaRoute
  '/pedagogico/turmas/$id/': typeof AuthenticatedPedagogicoTurmasIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/base-conhecimento': typeof AuthenticatedBaseConhecimentoRoute
  '/captacao': typeof AuthenticatedCaptacaoRoute
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/': typeof AuthenticatedIndexRoute
  '/administrativo/beneficios': typeof AuthenticatedAdministrativoBeneficiosRoute
  '/administrativo/materiais': typeof AuthenticatedAdministrativoMateriaisRoute
  '/administrativo/qualificacao': typeof AuthenticatedAdministrativoQualificacaoRoute
  '/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/financeiro/despesas': typeof AuthenticatedFinanceiroDespesasRoute
  '/financeiro/fornecedores': typeof AuthenticatedFinanceiroFornecedoresRoute
  '/financeiro/orcamento': typeof AuthenticatedFinanceiroOrcamentoRoute
  '/administrativo': typeof AuthenticatedAdministrativoIndexRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesIndexRoute
  '/financeiro': typeof AuthenticatedFinanceiroIndexRoute
  '/pedagogico': typeof AuthenticatedPedagogicoIndexRoute
  '/pedagogico/turmas/$id/aulas': typeof AuthenticatedPedagogicoTurmasIdAulasRoute
  '/pedagogico/turmas/$id/cursistas': typeof AuthenticatedPedagogicoTurmasIdCursistasRoute
  '/pedagogico/turmas/$id/frequencia': typeof AuthenticatedPedagogicoTurmasIdFrequenciaRoute
  '/pedagogico/turmas/$id': typeof AuthenticatedPedagogicoTurmasIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/administrativo': typeof AuthenticatedAdministrativoRouteWithChildren
  '/_authenticated/base-conhecimento': typeof AuthenticatedBaseConhecimentoRoute
  '/_authenticated/captacao': typeof AuthenticatedCaptacaoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/_authenticated/pedagogico': typeof AuthenticatedPedagogicoRouteWithChildren
  '/_authenticated/pendencias': typeof AuthenticatedPendenciasRoute
  '/_authenticated/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/administrativo/beneficios': typeof AuthenticatedAdministrativoBeneficiosRoute
  '/_authenticated/administrativo/materiais': typeof AuthenticatedAdministrativoMateriaisRoute
  '/_authenticated/administrativo/qualificacao': typeof AuthenticatedAdministrativoQualificacaoRoute
  '/_authenticated/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/_authenticated/financeiro/despesas': typeof AuthenticatedFinanceiroDespesasRoute
  '/_authenticated/financeiro/fornecedores': typeof AuthenticatedFinanceiroFornecedoresRoute
  '/_authenticated/financeiro/orcamento': typeof AuthenticatedFinanceiroOrcamentoRoute
  '/_authenticated/administrativo/': typeof AuthenticatedAdministrativoIndexRoute
  '/_authenticated/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/_authenticated/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/_authenticated/pedagogico/': typeof AuthenticatedPedagogicoIndexRoute
  '/_authenticated/pedagogico/turmas/$id': typeof AuthenticatedPedagogicoTurmasIdRouteWithChildren
  '/_authenticated/pedagogico/turmas/$id/aulas': typeof AuthenticatedPedagogicoTurmasIdAulasRoute
  '/_authenticated/pedagogico/turmas/$id/cursistas': typeof AuthenticatedPedagogicoTurmasIdCursistasRoute
  '/_authenticated/pedagogico/turmas/$id/frequencia': typeof AuthenticatedPedagogicoTurmasIdFrequenciaRoute
  '/_authenticated/pedagogico/turmas/$id/': typeof AuthenticatedPedagogicoTurmasIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/administrativo'
    | '/base-conhecimento'
    | '/captacao'
    | '/configuracoes'
    | '/financeiro'
    | '/pedagogico'
    | '/pendencias'
    | '/trocar-senha'
    | '/administrativo/beneficios'
    | '/administrativo/materiais'
    | '/administrativo/qualificacao'
    | '/configuracoes/usuarios'
    | '/financeiro/despesas'
    | '/financeiro/fornecedores'
    | '/financeiro/orcamento'
    | '/administrativo/'
    | '/configuracoes/'
    | '/financeiro/'
    | '/pedagogico/'
    | '/pedagogico/turmas/$id'
    | '/pedagogico/turmas/$id/aulas'
    | '/pedagogico/turmas/$id/cursistas'
    | '/pedagogico/turmas/$id/frequencia'
    | '/pedagogico/turmas/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/base-conhecimento'
    | '/captacao'
    | '/pendencias'
    | '/trocar-senha'
    | '/'
    | '/administrativo/beneficios'
    | '/administrativo/materiais'
    | '/administrativo/qualificacao'
    | '/configuracoes/usuarios'
    | '/financeiro/despesas'
    | '/financeiro/fornecedores'
    | '/financeiro/orcamento'
    | '/administrativo'
    | '/configuracoes'
    | '/financeiro'
    | '/pedagogico'
    | '/pedagogico/turmas/$id/aulas'
    | '/pedagogico/turmas/$id/cursistas'
    | '/pedagogico/turmas/$id/frequencia'
    | '/pedagogico/turmas/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/administrativo'
    | '/_authenticated/base-conhecimento'
    | '/_authenticated/captacao'
    | '/_authenticated/configuracoes'
    | '/_authenticated/financeiro'
    | '/_authenticated/pedagogico'
    | '/_authenticated/pendencias'
    | '/_authenticated/trocar-senha'
    | '/_authenticated/'
    | '/_authenticated/administrativo/beneficios'
    | '/_authenticated/administrativo/materiais'
    | '/_authenticated/administrativo/qualificacao'
    | '/_authenticated/configuracoes/usuarios'
    | '/_authenticated/financeiro/despesas'
    | '/_authenticated/financeiro/fornecedores'
    | '/_authenticated/financeiro/orcamento'
    | '/_authenticated/administrativo/'
    | '/_authenticated/configuracoes/'
    | '/_authenticated/financeiro/'
    | '/_authenticated/pedagogico/'
    | '/_authenticated/pedagogico/turmas/$id'
    | '/_authenticated/pedagogico/turmas/$id/aulas'
    | '/_authenticated/pedagogico/turmas/$id/cursistas'
    | '/_authenticated/pedagogico/turmas/$id/frequencia'
    | '/_authenticated/pedagogico/turmas/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trocar-senha': {
      id: '/_authenticated/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof AuthenticatedTrocarSenhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pendencias': {
      id: '/_authenticated/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof AuthenticatedPendenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedagogico': {
      id: '/_authenticated/pedagogico'
      path: '/pedagogico'
      fullPath: '/pedagogico'
      preLoaderRoute: typeof AuthenticatedPedagogicoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/captacao': {
      id: '/_authenticated/captacao'
      path: '/captacao'
      fullPath: '/captacao'
      preLoaderRoute: typeof AuthenticatedCaptacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/base-conhecimento': {
      id: '/_authenticated/base-conhecimento'
      path: '/base-conhecimento'
      fullPath: '/base-conhecimento'
      preLoaderRoute: typeof AuthenticatedBaseConhecimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administrativo': {
      id: '/_authenticated/administrativo'
      path: '/administrativo'
      fullPath: '/administrativo'
      preLoaderRoute: typeof AuthenticatedAdministrativoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedagogico/': {
      id: '/_authenticated/pedagogico/'
      path: '/'
      fullPath: '/pedagogico/'
      preLoaderRoute: typeof AuthenticatedPedagogicoIndexRouteImport
      parentRoute: typeof AuthenticatedPedagogicoRoute
    }
    '/_authenticated/financeiro/': {
      id: '/_authenticated/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AuthenticatedFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/configuracoes/': {
      id: '/_authenticated/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/administrativo/': {
      id: '/_authenticated/administrativo/'
      path: '/'
      fullPath: '/administrativo/'
      preLoaderRoute: typeof AuthenticatedAdministrativoIndexRouteImport
      parentRoute: typeof AuthenticatedAdministrativoRoute
    }
    '/_authenticated/financeiro/orcamento': {
      id: '/_authenticated/financeiro/orcamento'
      path: '/orcamento'
      fullPath: '/financeiro/orcamento'
      preLoaderRoute: typeof AuthenticatedFinanceiroOrcamentoRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/fornecedores': {
      id: '/_authenticated/financeiro/fornecedores'
      path: '/fornecedores'
      fullPath: '/financeiro/fornecedores'
      preLoaderRoute: typeof AuthenticatedFinanceiroFornecedoresRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/despesas': {
      id: '/_authenticated/financeiro/despesas'
      path: '/despesas'
      fullPath: '/financeiro/despesas'
      preLoaderRoute: typeof AuthenticatedFinanceiroDespesasRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/configuracoes/usuarios': {
      id: '/_authenticated/configuracoes/usuarios'
      path: '/usuarios'
      fullPath: '/configuracoes/usuarios'
      preLoaderRoute: typeof AuthenticatedConfiguracoesUsuariosRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/administrativo/qualificacao': {
      id: '/_authenticated/administrativo/qualificacao'
      path: '/qualificacao'
      fullPath: '/administrativo/qualificacao'
      preLoaderRoute: typeof AuthenticatedAdministrativoQualificacaoRouteImport
      parentRoute: typeof AuthenticatedAdministrativoRoute
    }
    '/_authenticated/administrativo/materiais': {
      id: '/_authenticated/administrativo/materiais'
      path: '/materiais'
      fullPath: '/administrativo/materiais'
      preLoaderRoute: typeof AuthenticatedAdministrativoMateriaisRouteImport
      parentRoute: typeof AuthenticatedAdministrativoRoute
    }
    '/_authenticated/administrativo/beneficios': {
      id: '/_authenticated/administrativo/beneficios'
      path: '/beneficios'
      fullPath: '/administrativo/beneficios'
      preLoaderRoute: typeof AuthenticatedAdministrativoBeneficiosRouteImport
      parentRoute: typeof AuthenticatedAdministrativoRoute
    }
    '/_authenticated/pedagogico/turmas/$id': {
      id: '/_authenticated/pedagogico/turmas/$id'
      path: '/turmas/$id'
      fullPath: '/pedagogico/turmas/$id'
      preLoaderRoute: typeof AuthenticatedPedagogicoTurmasIdRouteImport
      parentRoute: typeof AuthenticatedPedagogicoRoute
    }
    '/_authenticated/pedagogico/turmas/$id/': {
      id: '/_authenticated/pedagogico/turmas/$id/'
      path: '/'
      fullPath: '/pedagogico/turmas/$id/'
      preLoaderRoute: typeof AuthenticatedPedagogicoTurmasIdIndexRouteImport
      parentRoute: typeof AuthenticatedPedagogicoTurmasIdRoute
    }
    '/_authenticated/pedagogico/turmas/$id/frequencia': {
      id: '/_authenticated/pedagogico/turmas/$id/frequencia'
      path: '/frequencia'
      fullPath: '/pedagogico/turmas/$id/frequencia'
      preLoaderRoute: typeof AuthenticatedPedagogicoTurmasIdFrequenciaRouteImport
      parentRoute: typeof AuthenticatedPedagogicoTurmasIdRoute
    }
    '/_authenticated/pedagogico/turmas/$id/cursistas': {
      id: '/_authenticated/pedagogico/turmas/$id/cursistas'
      path: '/cursistas'
      fullPath: '/pedagogico/turmas/$id/cursistas'
      preLoaderRoute: typeof AuthenticatedPedagogicoTurmasIdCursistasRouteImport
      parentRoute: typeof AuthenticatedPedagogicoTurmasIdRoute
    }
    '/_authenticated/pedagogico/turmas/$id/aulas': {
      id: '/_authenticated/pedagogico/turmas/$id/aulas'
      path: '/aulas'
      fullPath: '/pedagogico/turmas/$id/aulas'
      preLoaderRoute: typeof AuthenticatedPedagogicoTurmasIdAulasRouteImport
      parentRoute: typeof AuthenticatedPedagogicoTurmasIdRoute
    }
  }
}

interface AuthenticatedAdministrativoRouteChildren {
  AuthenticatedAdministrativoBeneficiosRoute: typeof AuthenticatedAdministrativoBeneficiosRoute
  AuthenticatedAdministrativoMateriaisRoute: typeof AuthenticatedAdministrativoMateriaisRoute
  AuthenticatedAdministrativoQualificacaoRoute: typeof AuthenticatedAdministrativoQualificacaoRoute
  AuthenticatedAdministrativoIndexRoute: typeof AuthenticatedAdministrativoIndexRoute
}

const AuthenticatedAdministrativoRouteChildren: AuthenticatedAdministrativoRouteChildren =
  {
    AuthenticatedAdministrativoBeneficiosRoute:
      AuthenticatedAdministrativoBeneficiosRoute,
    AuthenticatedAdministrativoMateriaisRoute:
      AuthenticatedAdministrativoMateriaisRoute,
    AuthenticatedAdministrativoQualificacaoRoute:
      AuthenticatedAdministrativoQualificacaoRoute,
    AuthenticatedAdministrativoIndexRoute:
      AuthenticatedAdministrativoIndexRoute,
  }

const AuthenticatedAdministrativoRouteWithChildren =
  AuthenticatedAdministrativoRoute._addFileChildren(
    AuthenticatedAdministrativoRouteChildren,
  )

interface AuthenticatedConfiguracoesRouteChildren {
  AuthenticatedConfiguracoesUsuariosRoute: typeof AuthenticatedConfiguracoesUsuariosRoute
  AuthenticatedConfiguracoesIndexRoute: typeof AuthenticatedConfiguracoesIndexRoute
}

const AuthenticatedConfiguracoesRouteChildren: AuthenticatedConfiguracoesRouteChildren =
  {
    AuthenticatedConfiguracoesUsuariosRoute:
      AuthenticatedConfiguracoesUsuariosRoute,
    AuthenticatedConfiguracoesIndexRoute: AuthenticatedConfiguracoesIndexRoute,
  }

const AuthenticatedConfiguracoesRouteWithChildren =
  AuthenticatedConfiguracoesRoute._addFileChildren(
    AuthenticatedConfiguracoesRouteChildren,
  )

interface AuthenticatedFinanceiroRouteChildren {
  AuthenticatedFinanceiroDespesasRoute: typeof AuthenticatedFinanceiroDespesasRoute
  AuthenticatedFinanceiroFornecedoresRoute: typeof AuthenticatedFinanceiroFornecedoresRoute
  AuthenticatedFinanceiroOrcamentoRoute: typeof AuthenticatedFinanceiroOrcamentoRoute
  AuthenticatedFinanceiroIndexRoute: typeof AuthenticatedFinanceiroIndexRoute
}

const AuthenticatedFinanceiroRouteChildren: AuthenticatedFinanceiroRouteChildren =
  {
    AuthenticatedFinanceiroDespesasRoute: AuthenticatedFinanceiroDespesasRoute,
    AuthenticatedFinanceiroFornecedoresRoute:
      AuthenticatedFinanceiroFornecedoresRoute,
    AuthenticatedFinanceiroOrcamentoRoute:
      AuthenticatedFinanceiroOrcamentoRoute,
    AuthenticatedFinanceiroIndexRoute: AuthenticatedFinanceiroIndexRoute,
  }

const AuthenticatedFinanceiroRouteWithChildren =
  AuthenticatedFinanceiroRoute._addFileChildren(
    AuthenticatedFinanceiroRouteChildren,
  )

interface AuthenticatedPedagogicoTurmasIdRouteChildren {
  AuthenticatedPedagogicoTurmasIdAulasRoute: typeof AuthenticatedPedagogicoTurmasIdAulasRoute
  AuthenticatedPedagogicoTurmasIdCursistasRoute: typeof AuthenticatedPedagogicoTurmasIdCursistasRoute
  AuthenticatedPedagogicoTurmasIdFrequenciaRoute: typeof AuthenticatedPedagogicoTurmasIdFrequenciaRoute
  AuthenticatedPedagogicoTurmasIdIndexRoute: typeof AuthenticatedPedagogicoTurmasIdIndexRoute
}

const AuthenticatedPedagogicoTurmasIdRouteChildren: AuthenticatedPedagogicoTurmasIdRouteChildren =
  {
    AuthenticatedPedagogicoTurmasIdAulasRoute:
      AuthenticatedPedagogicoTurmasIdAulasRoute,
    AuthenticatedPedagogicoTurmasIdCursistasRoute:
      AuthenticatedPedagogicoTurmasIdCursistasRoute,
    AuthenticatedPedagogicoTurmasIdFrequenciaRoute:
      AuthenticatedPedagogicoTurmasIdFrequenciaRoute,
    AuthenticatedPedagogicoTurmasIdIndexRoute:
      AuthenticatedPedagogicoTurmasIdIndexRoute,
  }

const AuthenticatedPedagogicoTurmasIdRouteWithChildren =
  AuthenticatedPedagogicoTurmasIdRoute._addFileChildren(
    AuthenticatedPedagogicoTurmasIdRouteChildren,
  )

interface AuthenticatedPedagogicoRouteChildren {
  AuthenticatedPedagogicoIndexRoute: typeof AuthenticatedPedagogicoIndexRoute
  AuthenticatedPedagogicoTurmasIdRoute: typeof AuthenticatedPedagogicoTurmasIdRouteWithChildren
}

const AuthenticatedPedagogicoRouteChildren: AuthenticatedPedagogicoRouteChildren =
  {
    AuthenticatedPedagogicoIndexRoute: AuthenticatedPedagogicoIndexRoute,
    AuthenticatedPedagogicoTurmasIdRoute:
      AuthenticatedPedagogicoTurmasIdRouteWithChildren,
  }

const AuthenticatedPedagogicoRouteWithChildren =
  AuthenticatedPedagogicoRoute._addFileChildren(
    AuthenticatedPedagogicoRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministrativoRoute: typeof AuthenticatedAdministrativoRouteWithChildren
  AuthenticatedBaseConhecimentoRoute: typeof AuthenticatedBaseConhecimentoRoute
  AuthenticatedCaptacaoRoute: typeof AuthenticatedCaptacaoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRouteWithChildren
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRouteWithChildren
  AuthenticatedPedagogicoRoute: typeof AuthenticatedPedagogicoRouteWithChildren
  AuthenticatedPendenciasRoute: typeof AuthenticatedPendenciasRoute
  AuthenticatedTrocarSenhaRoute: typeof AuthenticatedTrocarSenhaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministrativoRoute:
    AuthenticatedAdministrativoRouteWithChildren,
  AuthenticatedBaseConhecimentoRoute: AuthenticatedBaseConhecimentoRoute,
  AuthenticatedCaptacaoRoute: AuthenticatedCaptacaoRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRouteWithChildren,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRouteWithChildren,
  AuthenticatedPedagogicoRoute: AuthenticatedPedagogicoRouteWithChildren,
  AuthenticatedPendenciasRoute: AuthenticatedPendenciasRoute,
  AuthenticatedTrocarSenhaRoute: AuthenticatedTrocarSenhaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
