/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MulheresConectadasRouteImport } from './routes/mulheres-conectadas'
import { Route as InscricaoRouteImport } from './routes/inscricao'
import { Route as ImprimirInscricaoRouteImport } from './routes/imprimir-inscricao'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedTrocarSenhaRouteImport } from './routes/_authenticated/trocar-senha'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedRelacaoHorasRouteImport } from './routes/_authenticated/relacao-horas'
import { Route as AuthenticatedPendenciasRouteImport } from './routes/_authenticated/pendencias'
import { Route as AuthenticatedPedagogicoRouteImport } from './routes/_authenticated/pedagogico'
import { Route as AuthenticatedMteRouteImport } from './routes/_authenticated/mte'
import { Route as AuthenticatedMinhasDemandasRouteImport } from './routes/_authenticated/minhas-demandas'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEtapasRouteImport } from './routes/_authenticated/etapas'
import { Route as AuthenticatedDriveRouteImport } from './routes/_authenticated/drive'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCaptacaoRouteImport } from './routes/_authenticated/captacao'
import { Route as AuthenticatedBaseConhecimentoRouteImport } from './routes/_authenticated/base-conhecimento'
import { Route as AuthenticatedAjudaRouteImport } from './routes/_authenticated/ajuda'
import { Route as AuthenticatedAdministrativoRouteImport } from './routes/_authenticated/administrativo'
import { Route as AuthenticatedWhatsappIndexRouteImport } from './routes/_authenticated/whatsapp.index'
import { Route as AuthenticatedRelatoriosIndexRouteImport } from './routes/_authenticated/relatorios.index'
import { Route as AuthenticatedPedagogicoIndexRouteImport } from './routes/_authenticated/pedagogico.index'
import { Route as AuthenticatedMteIndexRouteImport } from './routes/_authenticated/mte.index'
import { Route as AuthenticatedFinanceiroIndexRouteImport } from './routes/_authenticated/financeiro.index'
import { Route as AuthenticatedConfiguracoesIndexRouteImport } from './routes/_authenticated/configuracoes.index'
import { Route as AuthenticatedAdministrativoIndexRouteImport } from './routes/_authenticated/administrativo.index'
import { Route as AuthenticatedWhatsappImportacaoIdRouteImport } from './routes/_authenticated/whatsapp.$importacaoId'
import { Route as AuthenticatedRelatoriosPedagogicoRouteImport } from './routes/_authenticated/relatorios.pedagogico'
import { Route as AuthenticatedRelatoriosParcialObjetoRouteImport } from './routes/_authenticated/relatorios.parcial-objeto'
import { Route as AuthenticatedRelatoriosOrcamentarioRouteImport } from './routes/_authenticated/relatorios.orcamentario'
import { Route as AuthenticatedRelatoriosMteRouteImport } from './routes/_authenticated/relatorios.mte'
import { Route as AuthenticatedRelatoriosMetasRouteImport } from './routes/_authenticated/relatorios.metas'
import { Route as AuthenticatedRelatoriosIndicadoresRouteImport } from './routes/_authenticated/relatorios.indicadores'
import { Route as AuthenticatedRelatoriosFrequenciaRouteImport } from './routes/_authenticated/relatorios.frequencia'
import { Route as AuthenticatedMteTurmasRouteImport } from './routes/_authenticated/mte.turmas'
import { Route as AuthenticatedMtePresencasRouteImport } from './routes/_authenticated/mte.presencas'
import { Route as AuthenticatedMteMatriculasRouteImport } from './routes/_authenticated/mte.matriculas'
import { Route as AuthenticatedMteImportarListaRouteImport } from './routes/_authenticated/mte.importar-lista'
import { Route as AuthenticatedMteEvidenciasRouteImport } from './routes/_authenticated/mte.evidencias'
import { Route as AuthenticatedMteCronogramaRouteImport } from './routes/_authenticated/mte.cronograma'
import { Route as AuthenticatedMteChecklistRouteImport } from './routes/_authenticated/mte.checklist'
import { Route as AuthenticatedMteBeneficiariasRouteImport } from './routes/_authenticated/mte.beneficiarias'
import { Route as AuthenticatedMteAvaRouteImport } from './routes/_authenticated/mte.ava'
import { Route as AuthenticatedMteAulasRouteImport } from './routes/_authenticated/mte.aulas'
import { Route as AuthenticatedFinanceiroRubricasRouteImport } from './routes/_authenticated/financeiro.rubricas'
import { Route as AuthenticatedFinanceiroRelacoesHorasRouteImport } from './routes/_authenticated/financeiro.relacoes-horas'
import { Route as AuthenticatedFinanceiroOrcamentoRouteImport } from './routes/_authenticated/financeiro.orcamento'
import { Route as AuthenticatedFinanceiroFornecedoresRouteImport } from './routes/_authenticated/financeiro.fornecedores'
import { Route as AuthenticatedFinanceiroDespesasRouteImport } from './routes/_authenticated/financeiro.despesas'
import { Route as AuthenticatedFinanceiroConciliacaoRouteImport } from './routes/_authenticated/financeiro.conciliacao'
import { Route as AuthenticatedConfiguracoesUsuariosRouteImport } from './routes/_authenticated/configuracoes.usuarios'
import { Route as AuthenticatedConfiguracoesPermissoesRouteImport } from './routes/_authenticated/configuracoes.permissoes'
import { Route as AuthenticatedConfiguracoesLocaisRouteImport } from './routes/_authenticated/configuracoes.locais'
import { Route as AuthenticatedConfiguracoesInstrutorTurmasRouteImport } from './routes/_authenticated/configuracoes.instrutor-turmas'
import { Route as AuthenticatedConfiguracoesIaRouteImport } from './routes/_authenticated/configuracoes.ia'
import { Route as AuthenticatedAdministrativoQualificacaoRouteImport } from './routes/_authenticated/administrativo.qualificacao'
import { Route as AuthenticatedAdministrativoMateriaisRouteImport } from './routes/_authenticated/administrativo.materiais'
import { Route as AuthenticatedAdministrativoInscricoesRouteImport } from './routes/_authenticated/administrativo.inscricoes'
import { Route as AuthenticatedAdministrativoDepoimentosRouteImport } from './routes/_authenticated/administrativo.depoimentos'
import { Route as AuthenticatedAdministrativoBeneficiosRouteImport } from './routes/_authenticated/administrativo.beneficios'
import { Route as AuthenticatedPedagogicoTurmasIdRouteImport } from './routes/_authenticated/pedagogico.turmas.$id'
import { Route as AuthenticatedPedagogicoTurmasIdIndexRouteImport } from './routes/_authenticated/pedagogico.turmas.$id.index'
import { Route as AuthenticatedPedagogicoTurmasIdFrequenciaRouteImport } from './routes/_authenticated/pedagogico.turmas.$id.frequencia'
import { Route as AuthenticatedPedagogicoTurmasIdCursistasRouteImport } from './routes/_authenticated/pedagogico.turmas.$id.cursistas'
import { Route as AuthenticatedPedagogicoTurmasIdCertificadosRouteImport } from './routes/_authenticated/pedagogico.turmas.$id.certificados'
import { Route as AuthenticatedPedagogicoTurmasIdAulasRouteImport } from './routes/_authenticated/pedagogico.turmas.$id.aulas'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MulheresConectadasRoute = MulheresConectadasRouteImport.update({
  id: '/mulheres-conectadas',
  path: '/mulheres-conectadas',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRoute = InscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprimirInscricaoRoute = ImprimirInscricaoRouteImport.update({
  id: '/imprimir-inscricao',
  path: '/imprimir-inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrocarSenhaRoute =
  AuthenticatedTrocarSenhaRouteImport.update({
    id: '/trocar-senha',
    path: '/trocar-senha',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelacaoHorasRoute =
  AuthenticatedRelacaoHorasRouteImport.update({
    id: '/relacao-horas',
    path: '/relacao-horas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPendenciasRoute = AuthenticatedPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedagogicoRoute = AuthenticatedPedagogicoRouteImport.update({
  id: '/pedagogico',
  path: '/pedagogico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMteRoute = AuthenticatedMteRouteImport.update({
  id: '/mte',
  path: '/mte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhasDemandasRoute =
  AuthenticatedMinhasDemandasRouteImport.update({
    id: '/minhas-demandas',
    path: '/minhas-demandas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEtapasRoute = AuthenticatedEtapasRouteImport.update({
  id: '/etapas',
  path: '/etapas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriveRoute = AuthenticatedDriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaptacaoRoute = AuthenticatedCaptacaoRouteImport.update({
  id: '/captacao',
  path: '/captacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBaseConhecimentoRoute =
  AuthenticatedBaseConhecimentoRouteImport.update({
    id: '/base-conhecimento',
    path: '/base-conhecimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAjudaRoute = AuthenticatedAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdministrativoRoute =
  AuthenticatedAdministrativoRouteImport.update({
    id: '/administrativo',
    path: '/administrativo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappIndexRoute =
  AuthenticatedWhatsappIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWhatsappRoute,
  } as any)
const AuthenticatedRelatoriosIndexRoute =
  AuthenticatedRelatoriosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedPedagogicoIndexRoute =
  AuthenticatedPedagogicoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPedagogicoRoute,
  } as any)
const AuthenticatedMteIndexRoute = AuthenticatedMteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMteRoute,
} as any)
const AuthenticatedFinanceiroIndexRoute =
  AuthenticatedFinanceiroIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedConfiguracoesIndexRoute =
  AuthenticatedConfiguracoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedAdministrativoIndexRoute =
  AuthenticatedAdministrativoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdministrativoRoute,
  } as any)
const AuthenticatedWhatsappImportacaoIdRoute =
  AuthenticatedWhatsappImportacaoIdRouteImport.update({
    id: '/$importacaoId',
    path: '/$importacaoId',
    getParentRoute: () => AuthenticatedWhatsappRoute,
  } as any)
const AuthenticatedRelatoriosPedagogicoRoute =
  AuthenticatedRelatoriosPedagogicoRouteImport.update({
    id: '/pedagogico',
    path: '/pedagogico',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosParcialObjetoRoute =
  AuthenticatedRelatoriosParcialObjetoRouteImport.update({
    id: '/parcial-objeto',
    path: '/parcial-objeto',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosOrcamentarioRoute =
  AuthenticatedRelatoriosOrcamentarioRouteImport.update({
    id: '/orcamentario',
    path: '/orcamentario',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosMteRoute =
  AuthenticatedRelatoriosMteRouteImport.update({
    id: '/mte',
    path: '/mte',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosMetasRoute =
  AuthenticatedRelatoriosMetasRouteImport.update({
    id: '/metas',
    path: '/metas',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosIndicadoresRoute =
  AuthenticatedRelatoriosIndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosFrequenciaRoute =
  AuthenticatedRelatoriosFrequenciaRouteImport.update({
    id: '/frequencia',
    path: '/frequencia',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedMteTurmasRoute = AuthenticatedMteTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => AuthenticatedMteRoute,
} as any)
const AuthenticatedMtePresencasRoute =
  AuthenticatedMtePresencasRouteImport.update({
    id: '/presencas',
    path: '/presencas',
    getParentRoute: () => AuthenticatedMteRoute,
  } as any)
const AuthenticatedMteMatriculasRoute =
  AuthenticatedMteMatriculasRouteImport.update({
    id: '/matriculas',
    path: '/matriculas',
    getParentRoute: () => AuthenticatedMteRoute,
  } as any)
const AuthenticatedMteImportarListaRoute =
  AuthenticatedMteImportarListaRouteImport.update({
    id: '/importar-lista',
    path: '/importar-lista',
    getParentRoute: () => AuthenticatedMteRoute,
  } as any)
const AuthenticatedMteEvidenciasRoute =
  AuthenticatedMteEvidenciasRouteImport.update({
    id: '/evidencias',
    path: '/evidencias',
    getParentRoute: () => AuthenticatedMteRoute,
  } as any)
const AuthenticatedMteCronogramaRoute =
  AuthenticatedMteCronogramaRouteImport.update({
    id: '/cronograma',
    path: '/cronograma',
    getParentRoute: () => AuthenticatedMteRoute,
  } as any)
const AuthenticatedMteChecklistRoute =
  AuthenticatedMteChecklistRouteImport.update({
    id: '/checklist',
    path: '/checklist',
    getParentRoute: () => AuthenticatedMteRoute,
  } as any)
const AuthenticatedMteBeneficiariasRoute =
  AuthenticatedMteBeneficiariasRouteImport.update({
    id: '/beneficiarias',
    path: '/beneficiarias',
    getParentRoute: () => AuthenticatedMteRoute,
  } as any)
const AuthenticatedMteAvaRoute = AuthenticatedMteAvaRouteImport.update({
  id: '/ava',
  path: '/ava',
  getParentRoute: () => AuthenticatedMteRoute,
} as any)
const AuthenticatedMteAulasRoute = AuthenticatedMteAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AuthenticatedMteRoute,
} as any)
const AuthenticatedFinanceiroRubricasRoute =
  AuthenticatedFinanceiroRubricasRouteImport.update({
    id: '/rubricas',
    path: '/rubricas',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroRelacoesHorasRoute =
  AuthenticatedFinanceiroRelacoesHorasRouteImport.update({
    id: '/relacoes-horas',
    path: '/relacoes-horas',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroOrcamentoRoute =
  AuthenticatedFinanceiroOrcamentoRouteImport.update({
    id: '/orcamento',
    path: '/orcamento',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroFornecedoresRoute =
  AuthenticatedFinanceiroFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroDespesasRoute =
  AuthenticatedFinanceiroDespesasRouteImport.update({
    id: '/despesas',
    path: '/despesas',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroConciliacaoRoute =
  AuthenticatedFinanceiroConciliacaoRouteImport.update({
    id: '/conciliacao',
    path: '/conciliacao',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedConfiguracoesUsuariosRoute =
  AuthenticatedConfiguracoesUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesPermissoesRoute =
  AuthenticatedConfiguracoesPermissoesRouteImport.update({
    id: '/permissoes',
    path: '/permissoes',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesLocaisRoute =
  AuthenticatedConfiguracoesLocaisRouteImport.update({
    id: '/locais',
    path: '/locais',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesInstrutorTurmasRoute =
  AuthenticatedConfiguracoesInstrutorTurmasRouteImport.update({
    id: '/instrutor-turmas',
    path: '/instrutor-turmas',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesIaRoute =
  AuthenticatedConfiguracoesIaRouteImport.update({
    id: '/ia',
    path: '/ia',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedAdministrativoQualificacaoRoute =
  AuthenticatedAdministrativoQualificacaoRouteImport.update({
    id: '/qualificacao',
    path: '/qualificacao',
    getParentRoute: () => AuthenticatedAdministrativoRoute,
  } as any)
const AuthenticatedAdministrativoMateriaisRoute =
  AuthenticatedAdministrativoMateriaisRouteImport.update({
    id: '/materiais',
    path: '/materiais',
    getParentRoute: () => AuthenticatedAdministrativoRoute,
  } as any)
const AuthenticatedAdministrativoInscricoesRoute =
  AuthenticatedAdministrativoInscricoesRouteImport.update({
    id: '/inscricoes',
    path: '/inscricoes',
    getParentRoute: () => AuthenticatedAdministrativoRoute,
  } as any)
const AuthenticatedAdministrativoDepoimentosRoute =
  AuthenticatedAdministrativoDepoimentosRouteImport.update({
    id: '/depoimentos',
    path: '/depoimentos',
    getParentRoute: () => AuthenticatedAdministrativoRoute,
  } as any)
const AuthenticatedAdministrativoBeneficiosRoute =
  AuthenticatedAdministrativoBeneficiosRouteImport.update({
    id: '/beneficios',
    path: '/beneficios',
    getParentRoute: () => AuthenticatedAdministrativoRoute,
  } as any)
const AuthenticatedPedagogicoTurmasIdRoute =
  AuthenticatedPedagogicoTurmasIdRouteImport.update({
    id: '/turmas/$id',
    path: '/turmas/$id',
    getParentRoute: () => AuthenticatedPedagogicoRoute,
  } as any)
const AuthenticatedPedagogicoTurmasIdIndexRoute =
  AuthenticatedPedagogicoTurmasIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPedagogicoTurmasIdRoute,
  } as any)
const AuthenticatedPedagogicoTurmasIdFrequenciaRoute =
  AuthenticatedPedagogicoTurmasIdFrequenciaRouteImport.update({
    id: '/frequencia',
    path: '/frequencia',
    getParentRoute: () => AuthenticatedPedagogicoTurmasIdRoute,
  } as any)
const AuthenticatedPedagogicoTurmasIdCursistasRoute =
  AuthenticatedPedagogicoTurmasIdCursistasRouteImport.update({
    id: '/cursistas',
    path: '/cursistas',
    getParentRoute: () => AuthenticatedPedagogicoTurmasIdRoute,
  } as any)
const AuthenticatedPedagogicoTurmasIdCertificadosRoute =
  AuthenticatedPedagogicoTurmasIdCertificadosRouteImport.update({
    id: '/certificados',
    path: '/certificados',
    getParentRoute: () => AuthenticatedPedagogicoTurmasIdRoute,
  } as any)
const AuthenticatedPedagogicoTurmasIdAulasRoute =
  AuthenticatedPedagogicoTurmasIdAulasRouteImport.update({
    id: '/aulas',
    path: '/aulas',
    getParentRoute: () => AuthenticatedPedagogicoTurmasIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/imprimir-inscricao': typeof ImprimirInscricaoRoute
  '/inscricao': typeof InscricaoRoute
  '/mulheres-conectadas': typeof MulheresConectadasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/administrativo': typeof AuthenticatedAdministrativoRouteWithChildren
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/base-conhecimento': typeof AuthenticatedBaseConhecimentoRoute
  '/captacao': typeof AuthenticatedCaptacaoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/drive': typeof AuthenticatedDriveRoute
  '/etapas': typeof AuthenticatedEtapasRoute
  '/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/minhas-demandas': typeof AuthenticatedMinhasDemandasRoute
  '/mte': typeof AuthenticatedMteRouteWithChildren
  '/pedagogico': typeof AuthenticatedPedagogicoRouteWithChildren
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/relacao-horas': typeof AuthenticatedRelacaoHorasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRouteWithChildren
  '/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/whatsapp': typeof AuthenticatedWhatsappRouteWithChildren
  '/administrativo/beneficios': typeof AuthenticatedAdministrativoBeneficiosRoute
  '/administrativo/depoimentos': typeof AuthenticatedAdministrativoDepoimentosRoute
  '/administrativo/inscricoes': typeof AuthenticatedAdministrativoInscricoesRoute
  '/administrativo/materiais': typeof AuthenticatedAdministrativoMateriaisRoute
  '/administrativo/qualificacao': typeof AuthenticatedAdministrativoQualificacaoRoute
  '/configuracoes/ia': typeof AuthenticatedConfiguracoesIaRoute
  '/configuracoes/instrutor-turmas': typeof AuthenticatedConfiguracoesInstrutorTurmasRoute
  '/configuracoes/locais': typeof AuthenticatedConfiguracoesLocaisRoute
  '/configuracoes/permissoes': typeof AuthenticatedConfiguracoesPermissoesRoute
  '/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/financeiro/despesas': typeof AuthenticatedFinanceiroDespesasRoute
  '/financeiro/fornecedores': typeof AuthenticatedFinanceiroFornecedoresRoute
  '/financeiro/orcamento': typeof AuthenticatedFinanceiroOrcamentoRoute
  '/financeiro/relacoes-horas': typeof AuthenticatedFinanceiroRelacoesHorasRoute
  '/financeiro/rubricas': typeof AuthenticatedFinanceiroRubricasRoute
  '/mte/aulas': typeof AuthenticatedMteAulasRoute
  '/mte/ava': typeof AuthenticatedMteAvaRoute
  '/mte/beneficiarias': typeof AuthenticatedMteBeneficiariasRoute
  '/mte/checklist': typeof AuthenticatedMteChecklistRoute
  '/mte/cronograma': typeof AuthenticatedMteCronogramaRoute
  '/mte/evidencias': typeof AuthenticatedMteEvidenciasRoute
  '/mte/importar-lista': typeof AuthenticatedMteImportarListaRoute
  '/mte/matriculas': typeof AuthenticatedMteMatriculasRoute
  '/mte/presencas': typeof AuthenticatedMtePresencasRoute
  '/mte/turmas': typeof AuthenticatedMteTurmasRoute
  '/relatorios/frequencia': typeof AuthenticatedRelatoriosFrequenciaRoute
  '/relatorios/indicadores': typeof AuthenticatedRelatoriosIndicadoresRoute
  '/relatorios/metas': typeof AuthenticatedRelatoriosMetasRoute
  '/relatorios/mte': typeof AuthenticatedRelatoriosMteRoute
  '/relatorios/orcamentario': typeof AuthenticatedRelatoriosOrcamentarioRoute
  '/relatorios/parcial-objeto': typeof AuthenticatedRelatoriosParcialObjetoRoute
  '/relatorios/pedagogico': typeof AuthenticatedRelatoriosPedagogicoRoute
  '/whatsapp/$importacaoId': typeof AuthenticatedWhatsappImportacaoIdRoute
  '/administrativo/': typeof AuthenticatedAdministrativoIndexRoute
  '/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/mte/': typeof AuthenticatedMteIndexRoute
  '/pedagogico/': typeof AuthenticatedPedagogicoIndexRoute
  '/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
  '/whatsapp/': typeof AuthenticatedWhatsappIndexRoute
  '/pedagogico/turmas/$id': typeof AuthenticatedPedagogicoTurmasIdRouteWithChildren
  '/pedagogico/turmas/$id/aulas': typeof AuthenticatedPedagogicoTurmasIdAulasRoute
  '/pedagogico/turmas/$id/certificados': typeof AuthenticatedPedagogicoTurmasIdCertificadosRoute
  '/pedagogico/turmas/$id/cursistas': typeof AuthenticatedPedagogicoTurmasIdCursistasRoute
  '/pedagogico/turmas/$id/frequencia': typeof AuthenticatedPedagogicoTurmasIdFrequenciaRoute
  '/pedagogico/turmas/$id/': typeof AuthenticatedPedagogicoTurmasIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/imprimir-inscricao': typeof ImprimirInscricaoRoute
  '/inscricao': typeof InscricaoRoute
  '/mulheres-conectadas': typeof MulheresConectadasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/base-conhecimento': typeof AuthenticatedBaseConhecimentoRoute
  '/captacao': typeof AuthenticatedCaptacaoRoute
  '/drive': typeof AuthenticatedDriveRoute
  '/etapas': typeof AuthenticatedEtapasRoute
  '/minhas-demandas': typeof AuthenticatedMinhasDemandasRoute
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/relacao-horas': typeof AuthenticatedRelacaoHorasRoute
  '/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/': typeof AuthenticatedIndexRoute
  '/administrativo/beneficios': typeof AuthenticatedAdministrativoBeneficiosRoute
  '/administrativo/depoimentos': typeof AuthenticatedAdministrativoDepoimentosRoute
  '/administrativo/inscricoes': typeof AuthenticatedAdministrativoInscricoesRoute
  '/administrativo/materiais': typeof AuthenticatedAdministrativoMateriaisRoute
  '/administrativo/qualificacao': typeof AuthenticatedAdministrativoQualificacaoRoute
  '/configuracoes/ia': typeof AuthenticatedConfiguracoesIaRoute
  '/configuracoes/instrutor-turmas': typeof AuthenticatedConfiguracoesInstrutorTurmasRoute
  '/configuracoes/locais': typeof AuthenticatedConfiguracoesLocaisRoute
  '/configuracoes/permissoes': typeof AuthenticatedConfiguracoesPermissoesRoute
  '/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/financeiro/despesas': typeof AuthenticatedFinanceiroDespesasRoute
  '/financeiro/fornecedores': typeof AuthenticatedFinanceiroFornecedoresRoute
  '/financeiro/orcamento': typeof AuthenticatedFinanceiroOrcamentoRoute
  '/financeiro/relacoes-horas': typeof AuthenticatedFinanceiroRelacoesHorasRoute
  '/financeiro/rubricas': typeof AuthenticatedFinanceiroRubricasRoute
  '/mte/aulas': typeof AuthenticatedMteAulasRoute
  '/mte/ava': typeof AuthenticatedMteAvaRoute
  '/mte/beneficiarias': typeof AuthenticatedMteBeneficiariasRoute
  '/mte/checklist': typeof AuthenticatedMteChecklistRoute
  '/mte/cronograma': typeof AuthenticatedMteCronogramaRoute
  '/mte/evidencias': typeof AuthenticatedMteEvidenciasRoute
  '/mte/importar-lista': typeof AuthenticatedMteImportarListaRoute
  '/mte/matriculas': typeof AuthenticatedMteMatriculasRoute
  '/mte/presencas': typeof AuthenticatedMtePresencasRoute
  '/mte/turmas': typeof AuthenticatedMteTurmasRoute
  '/relatorios/frequencia': typeof AuthenticatedRelatoriosFrequenciaRoute
  '/relatorios/indicadores': typeof AuthenticatedRelatoriosIndicadoresRoute
  '/relatorios/metas': typeof AuthenticatedRelatoriosMetasRoute
  '/relatorios/mte': typeof AuthenticatedRelatoriosMteRoute
  '/relatorios/orcamentario': typeof AuthenticatedRelatoriosOrcamentarioRoute
  '/relatorios/parcial-objeto': typeof AuthenticatedRelatoriosParcialObjetoRoute
  '/relatorios/pedagogico': typeof AuthenticatedRelatoriosPedagogicoRoute
  '/whatsapp/$importacaoId': typeof AuthenticatedWhatsappImportacaoIdRoute
  '/administrativo': typeof AuthenticatedAdministrativoIndexRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesIndexRoute
  '/financeiro': typeof AuthenticatedFinanceiroIndexRoute
  '/mte': typeof AuthenticatedMteIndexRoute
  '/pedagogico': typeof AuthenticatedPedagogicoIndexRoute
  '/relatorios': typeof AuthenticatedRelatoriosIndexRoute
  '/whatsapp': typeof AuthenticatedWhatsappIndexRoute
  '/pedagogico/turmas/$id/aulas': typeof AuthenticatedPedagogicoTurmasIdAulasRoute
  '/pedagogico/turmas/$id/certificados': typeof AuthenticatedPedagogicoTurmasIdCertificadosRoute
  '/pedagogico/turmas/$id/cursistas': typeof AuthenticatedPedagogicoTurmasIdCursistasRoute
  '/pedagogico/turmas/$id/frequencia': typeof AuthenticatedPedagogicoTurmasIdFrequenciaRoute
  '/pedagogico/turmas/$id': typeof AuthenticatedPedagogicoTurmasIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/imprimir-inscricao': typeof ImprimirInscricaoRoute
  '/inscricao': typeof InscricaoRoute
  '/mulheres-conectadas': typeof MulheresConectadasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/administrativo': typeof AuthenticatedAdministrativoRouteWithChildren
  '/_authenticated/ajuda': typeof AuthenticatedAjudaRoute
  '/_authenticated/base-conhecimento': typeof AuthenticatedBaseConhecimentoRoute
  '/_authenticated/captacao': typeof AuthenticatedCaptacaoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/_authenticated/drive': typeof AuthenticatedDriveRoute
  '/_authenticated/etapas': typeof AuthenticatedEtapasRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/_authenticated/minhas-demandas': typeof AuthenticatedMinhasDemandasRoute
  '/_authenticated/mte': typeof AuthenticatedMteRouteWithChildren
  '/_authenticated/pedagogico': typeof AuthenticatedPedagogicoRouteWithChildren
  '/_authenticated/pendencias': typeof AuthenticatedPendenciasRoute
  '/_authenticated/relacao-horas': typeof AuthenticatedRelacaoHorasRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRouteWithChildren
  '/_authenticated/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/administrativo/beneficios': typeof AuthenticatedAdministrativoBeneficiosRoute
  '/_authenticated/administrativo/depoimentos': typeof AuthenticatedAdministrativoDepoimentosRoute
  '/_authenticated/administrativo/inscricoes': typeof AuthenticatedAdministrativoInscricoesRoute
  '/_authenticated/administrativo/materiais': typeof AuthenticatedAdministrativoMateriaisRoute
  '/_authenticated/administrativo/qualificacao': typeof AuthenticatedAdministrativoQualificacaoRoute
  '/_authenticated/configuracoes/ia': typeof AuthenticatedConfiguracoesIaRoute
  '/_authenticated/configuracoes/instrutor-turmas': typeof AuthenticatedConfiguracoesInstrutorTurmasRoute
  '/_authenticated/configuracoes/locais': typeof AuthenticatedConfiguracoesLocaisRoute
  '/_authenticated/configuracoes/permissoes': typeof AuthenticatedConfiguracoesPermissoesRoute
  '/_authenticated/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/_authenticated/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/_authenticated/financeiro/despesas': typeof AuthenticatedFinanceiroDespesasRoute
  '/_authenticated/financeiro/fornecedores': typeof AuthenticatedFinanceiroFornecedoresRoute
  '/_authenticated/financeiro/orcamento': typeof AuthenticatedFinanceiroOrcamentoRoute
  '/_authenticated/financeiro/relacoes-horas': typeof AuthenticatedFinanceiroRelacoesHorasRoute
  '/_authenticated/financeiro/rubricas': typeof AuthenticatedFinanceiroRubricasRoute
  '/_authenticated/mte/aulas': typeof AuthenticatedMteAulasRoute
  '/_authenticated/mte/ava': typeof AuthenticatedMteAvaRoute
  '/_authenticated/mte/beneficiarias': typeof AuthenticatedMteBeneficiariasRoute
  '/_authenticated/mte/checklist': typeof AuthenticatedMteChecklistRoute
  '/_authenticated/mte/cronograma': typeof AuthenticatedMteCronogramaRoute
  '/_authenticated/mte/evidencias': typeof AuthenticatedMteEvidenciasRoute
  '/_authenticated/mte/importar-lista': typeof AuthenticatedMteImportarListaRoute
  '/_authenticated/mte/matriculas': typeof AuthenticatedMteMatriculasRoute
  '/_authenticated/mte/presencas': typeof AuthenticatedMtePresencasRoute
  '/_authenticated/mte/turmas': typeof AuthenticatedMteTurmasRoute
  '/_authenticated/relatorios/frequencia': typeof AuthenticatedRelatoriosFrequenciaRoute
  '/_authenticated/relatorios/indicadores': typeof AuthenticatedRelatoriosIndicadoresRoute
  '/_authenticated/relatorios/metas': typeof AuthenticatedRelatoriosMetasRoute
  '/_authenticated/relatorios/mte': typeof AuthenticatedRelatoriosMteRoute
  '/_authenticated/relatorios/orcamentario': typeof AuthenticatedRelatoriosOrcamentarioRoute
  '/_authenticated/relatorios/parcial-objeto': typeof AuthenticatedRelatoriosParcialObjetoRoute
  '/_authenticated/relatorios/pedagogico': typeof AuthenticatedRelatoriosPedagogicoRoute
  '/_authenticated/whatsapp/$importacaoId': typeof AuthenticatedWhatsappImportacaoIdRoute
  '/_authenticated/administrativo/': typeof AuthenticatedAdministrativoIndexRoute
  '/_authenticated/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/_authenticated/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/_authenticated/mte/': typeof AuthenticatedMteIndexRoute
  '/_authenticated/pedagogico/': typeof AuthenticatedPedagogicoIndexRoute
  '/_authenticated/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
  '/_authenticated/whatsapp/': typeof AuthenticatedWhatsappIndexRoute
  '/_authenticated/pedagogico/turmas/$id': typeof AuthenticatedPedagogicoTurmasIdRouteWithChildren
  '/_authenticated/pedagogico/turmas/$id/aulas': typeof AuthenticatedPedagogicoTurmasIdAulasRoute
  '/_authenticated/pedagogico/turmas/$id/certificados': typeof AuthenticatedPedagogicoTurmasIdCertificadosRoute
  '/_authenticated/pedagogico/turmas/$id/cursistas': typeof AuthenticatedPedagogicoTurmasIdCursistasRoute
  '/_authenticated/pedagogico/turmas/$id/frequencia': typeof AuthenticatedPedagogicoTurmasIdFrequenciaRoute
  '/_authenticated/pedagogico/turmas/$id/': typeof AuthenticatedPedagogicoTurmasIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/imprimir-inscricao'
    | '/inscricao'
    | '/mulheres-conectadas'
    | '/reset-password'
    | '/administrativo'
    | '/ajuda'
    | '/base-conhecimento'
    | '/captacao'
    | '/configuracoes'
    | '/drive'
    | '/etapas'
    | '/financeiro'
    | '/minhas-demandas'
    | '/mte'
    | '/pedagogico'
    | '/pendencias'
    | '/relacao-horas'
    | '/relatorios'
    | '/trocar-senha'
    | '/whatsapp'
    | '/administrativo/beneficios'
    | '/administrativo/depoimentos'
    | '/administrativo/inscricoes'
    | '/administrativo/materiais'
    | '/administrativo/qualificacao'
    | '/configuracoes/ia'
    | '/configuracoes/instrutor-turmas'
    | '/configuracoes/locais'
    | '/configuracoes/permissoes'
    | '/configuracoes/usuarios'
    | '/financeiro/conciliacao'
    | '/financeiro/despesas'
    | '/financeiro/fornecedores'
    | '/financeiro/orcamento'
    | '/financeiro/relacoes-horas'
    | '/financeiro/rubricas'
    | '/mte/aulas'
    | '/mte/ava'
    | '/mte/beneficiarias'
    | '/mte/checklist'
    | '/mte/cronograma'
    | '/mte/evidencias'
    | '/mte/importar-lista'
    | '/mte/matriculas'
    | '/mte/presencas'
    | '/mte/turmas'
    | '/relatorios/frequencia'
    | '/relatorios/indicadores'
    | '/relatorios/metas'
    | '/relatorios/mte'
    | '/relatorios/orcamentario'
    | '/relatorios/parcial-objeto'
    | '/relatorios/pedagogico'
    | '/whatsapp/$importacaoId'
    | '/administrativo/'
    | '/configuracoes/'
    | '/financeiro/'
    | '/mte/'
    | '/pedagogico/'
    | '/relatorios/'
    | '/whatsapp/'
    | '/pedagogico/turmas/$id'
    | '/pedagogico/turmas/$id/aulas'
    | '/pedagogico/turmas/$id/certificados'
    | '/pedagogico/turmas/$id/cursistas'
    | '/pedagogico/turmas/$id/frequencia'
    | '/pedagogico/turmas/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/imprimir-inscricao'
    | '/inscricao'
    | '/mulheres-conectadas'
    | '/reset-password'
    | '/ajuda'
    | '/base-conhecimento'
    | '/captacao'
    | '/drive'
    | '/etapas'
    | '/minhas-demandas'
    | '/pendencias'
    | '/relacao-horas'
    | '/trocar-senha'
    | '/'
    | '/administrativo/beneficios'
    | '/administrativo/depoimentos'
    | '/administrativo/inscricoes'
    | '/administrativo/materiais'
    | '/administrativo/qualificacao'
    | '/configuracoes/ia'
    | '/configuracoes/instrutor-turmas'
    | '/configuracoes/locais'
    | '/configuracoes/permissoes'
    | '/configuracoes/usuarios'
    | '/financeiro/conciliacao'
    | '/financeiro/despesas'
    | '/financeiro/fornecedores'
    | '/financeiro/orcamento'
    | '/financeiro/relacoes-horas'
    | '/financeiro/rubricas'
    | '/mte/aulas'
    | '/mte/ava'
    | '/mte/beneficiarias'
    | '/mte/checklist'
    | '/mte/cronograma'
    | '/mte/evidencias'
    | '/mte/importar-lista'
    | '/mte/matriculas'
    | '/mte/presencas'
    | '/mte/turmas'
    | '/relatorios/frequencia'
    | '/relatorios/indicadores'
    | '/relatorios/metas'
    | '/relatorios/mte'
    | '/relatorios/orcamentario'
    | '/relatorios/parcial-objeto'
    | '/relatorios/pedagogico'
    | '/whatsapp/$importacaoId'
    | '/administrativo'
    | '/configuracoes'
    | '/financeiro'
    | '/mte'
    | '/pedagogico'
    | '/relatorios'
    | '/whatsapp'
    | '/pedagogico/turmas/$id/aulas'
    | '/pedagogico/turmas/$id/certificados'
    | '/pedagogico/turmas/$id/cursistas'
    | '/pedagogico/turmas/$id/frequencia'
    | '/pedagogico/turmas/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/imprimir-inscricao'
    | '/inscricao'
    | '/mulheres-conectadas'
    | '/reset-password'
    | '/_authenticated/administrativo'
    | '/_authenticated/ajuda'
    | '/_authenticated/base-conhecimento'
    | '/_authenticated/captacao'
    | '/_authenticated/configuracoes'
    | '/_authenticated/drive'
    | '/_authenticated/etapas'
    | '/_authenticated/financeiro'
    | '/_authenticated/minhas-demandas'
    | '/_authenticated/mte'
    | '/_authenticated/pedagogico'
    | '/_authenticated/pendencias'
    | '/_authenticated/relacao-horas'
    | '/_authenticated/relatorios'
    | '/_authenticated/trocar-senha'
    | '/_authenticated/whatsapp'
    | '/_authenticated/'
    | '/_authenticated/administrativo/beneficios'
    | '/_authenticated/administrativo/depoimentos'
    | '/_authenticated/administrativo/inscricoes'
    | '/_authenticated/administrativo/materiais'
    | '/_authenticated/administrativo/qualificacao'
    | '/_authenticated/configuracoes/ia'
    | '/_authenticated/configuracoes/instrutor-turmas'
    | '/_authenticated/configuracoes/locais'
    | '/_authenticated/configuracoes/permissoes'
    | '/_authenticated/configuracoes/usuarios'
    | '/_authenticated/financeiro/conciliacao'
    | '/_authenticated/financeiro/despesas'
    | '/_authenticated/financeiro/fornecedores'
    | '/_authenticated/financeiro/orcamento'
    | '/_authenticated/financeiro/relacoes-horas'
    | '/_authenticated/financeiro/rubricas'
    | '/_authenticated/mte/aulas'
    | '/_authenticated/mte/ava'
    | '/_authenticated/mte/beneficiarias'
    | '/_authenticated/mte/checklist'
    | '/_authenticated/mte/cronograma'
    | '/_authenticated/mte/evidencias'
    | '/_authenticated/mte/importar-lista'
    | '/_authenticated/mte/matriculas'
    | '/_authenticated/mte/presencas'
    | '/_authenticated/mte/turmas'
    | '/_authenticated/relatorios/frequencia'
    | '/_authenticated/relatorios/indicadores'
    | '/_authenticated/relatorios/metas'
    | '/_authenticated/relatorios/mte'
    | '/_authenticated/relatorios/orcamentario'
    | '/_authenticated/relatorios/parcial-objeto'
    | '/_authenticated/relatorios/pedagogico'
    | '/_authenticated/whatsapp/$importacaoId'
    | '/_authenticated/administrativo/'
    | '/_authenticated/configuracoes/'
    | '/_authenticated/financeiro/'
    | '/_authenticated/mte/'
    | '/_authenticated/pedagogico/'
    | '/_authenticated/relatorios/'
    | '/_authenticated/whatsapp/'
    | '/_authenticated/pedagogico/turmas/$id'
    | '/_authenticated/pedagogico/turmas/$id/aulas'
    | '/_authenticated/pedagogico/turmas/$id/certificados'
    | '/_authenticated/pedagogico/turmas/$id/cursistas'
    | '/_authenticated/pedagogico/turmas/$id/frequencia'
    | '/_authenticated/pedagogico/turmas/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ImprimirInscricaoRoute: typeof ImprimirInscricaoRoute
  InscricaoRoute: typeof InscricaoRoute
  MulheresConectadasRoute: typeof MulheresConectadasRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mulheres-conectadas': {
      id: '/mulheres-conectadas'
      path: '/mulheres-conectadas'
      fullPath: '/mulheres-conectadas'
      preLoaderRoute: typeof MulheresConectadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao': {
      id: '/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof InscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprimir-inscricao': {
      id: '/imprimir-inscricao'
      path: '/imprimir-inscricao'
      fullPath: '/imprimir-inscricao'
      preLoaderRoute: typeof ImprimirInscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trocar-senha': {
      id: '/_authenticated/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof AuthenticatedTrocarSenhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relacao-horas': {
      id: '/_authenticated/relacao-horas'
      path: '/relacao-horas'
      fullPath: '/relacao-horas'
      preLoaderRoute: typeof AuthenticatedRelacaoHorasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pendencias': {
      id: '/_authenticated/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof AuthenticatedPendenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedagogico': {
      id: '/_authenticated/pedagogico'
      path: '/pedagogico'
      fullPath: '/pedagogico'
      preLoaderRoute: typeof AuthenticatedPedagogicoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mte': {
      id: '/_authenticated/mte'
      path: '/mte'
      fullPath: '/mte'
      preLoaderRoute: typeof AuthenticatedMteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-demandas': {
      id: '/_authenticated/minhas-demandas'
      path: '/minhas-demandas'
      fullPath: '/minhas-demandas'
      preLoaderRoute: typeof AuthenticatedMinhasDemandasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/etapas': {
      id: '/_authenticated/etapas'
      path: '/etapas'
      fullPath: '/etapas'
      preLoaderRoute: typeof AuthenticatedEtapasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drive': {
      id: '/_authenticated/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof AuthenticatedDriveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/captacao': {
      id: '/_authenticated/captacao'
      path: '/captacao'
      fullPath: '/captacao'
      preLoaderRoute: typeof AuthenticatedCaptacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/base-conhecimento': {
      id: '/_authenticated/base-conhecimento'
      path: '/base-conhecimento'
      fullPath: '/base-conhecimento'
      preLoaderRoute: typeof AuthenticatedBaseConhecimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajuda': {
      id: '/_authenticated/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AuthenticatedAjudaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administrativo': {
      id: '/_authenticated/administrativo'
      path: '/administrativo'
      fullPath: '/administrativo'
      preLoaderRoute: typeof AuthenticatedAdministrativoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp/': {
      id: '/_authenticated/whatsapp/'
      path: '/'
      fullPath: '/whatsapp/'
      preLoaderRoute: typeof AuthenticatedWhatsappIndexRouteImport
      parentRoute: typeof AuthenticatedWhatsappRoute
    }
    '/_authenticated/relatorios/': {
      id: '/_authenticated/relatorios/'
      path: '/'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof AuthenticatedRelatoriosIndexRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/pedagogico/': {
      id: '/_authenticated/pedagogico/'
      path: '/'
      fullPath: '/pedagogico/'
      preLoaderRoute: typeof AuthenticatedPedagogicoIndexRouteImport
      parentRoute: typeof AuthenticatedPedagogicoRoute
    }
    '/_authenticated/mte/': {
      id: '/_authenticated/mte/'
      path: '/'
      fullPath: '/mte/'
      preLoaderRoute: typeof AuthenticatedMteIndexRouteImport
      parentRoute: typeof AuthenticatedMteRoute
    }
    '/_authenticated/financeiro/': {
      id: '/_authenticated/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AuthenticatedFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/configuracoes/': {
      id: '/_authenticated/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/administrativo/': {
      id: '/_authenticated/administrativo/'
      path: '/'
      fullPath: '/administrativo/'
      preLoaderRoute: typeof AuthenticatedAdministrativoIndexRouteImport
      parentRoute: typeof AuthenticatedAdministrativoRoute
    }
    '/_authenticated/whatsapp/$importacaoId': {
      id: '/_authenticated/whatsapp/$importacaoId'
      path: '/$importacaoId'
      fullPath: '/whatsapp/$importacaoId'
      preLoaderRoute: typeof AuthenticatedWhatsappImportacaoIdRouteImport
      parentRoute: typeof AuthenticatedWhatsappRoute
    }
    '/_authenticated/relatorios/pedagogico': {
      id: '/_authenticated/relatorios/pedagogico'
      path: '/pedagogico'
      fullPath: '/relatorios/pedagogico'
      preLoaderRoute: typeof AuthenticatedRelatoriosPedagogicoRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/parcial-objeto': {
      id: '/_authenticated/relatorios/parcial-objeto'
      path: '/parcial-objeto'
      fullPath: '/relatorios/parcial-objeto'
      preLoaderRoute: typeof AuthenticatedRelatoriosParcialObjetoRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/orcamentario': {
      id: '/_authenticated/relatorios/orcamentario'
      path: '/orcamentario'
      fullPath: '/relatorios/orcamentario'
      preLoaderRoute: typeof AuthenticatedRelatoriosOrcamentarioRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/mte': {
      id: '/_authenticated/relatorios/mte'
      path: '/mte'
      fullPath: '/relatorios/mte'
      preLoaderRoute: typeof AuthenticatedRelatoriosMteRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/metas': {
      id: '/_authenticated/relatorios/metas'
      path: '/metas'
      fullPath: '/relatorios/metas'
      preLoaderRoute: typeof AuthenticatedRelatoriosMetasRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/indicadores': {
      id: '/_authenticated/relatorios/indicadores'
      path: '/indicadores'
      fullPath: '/relatorios/indicadores'
      preLoaderRoute: typeof AuthenticatedRelatoriosIndicadoresRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/frequencia': {
      id: '/_authenticated/relatorios/frequencia'
      path: '/frequencia'
      fullPath: '/relatorios/frequencia'
      preLoaderRoute: typeof AuthenticatedRelatoriosFrequenciaRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/mte/turmas': {
      id: '/_authenticated/mte/turmas'
      path: '/turmas'
      fullPath: '/mte/turmas'
      preLoaderRoute: typeof AuthenticatedMteTurmasRouteImport
      parentRoute: typeof AuthenticatedMteRoute
    }
    '/_authenticated/mte/presencas': {
      id: '/_authenticated/mte/presencas'
      path: '/presencas'
      fullPath: '/mte/presencas'
      preLoaderRoute: typeof AuthenticatedMtePresencasRouteImport
      parentRoute: typeof AuthenticatedMteRoute
    }
    '/_authenticated/mte/matriculas': {
      id: '/_authenticated/mte/matriculas'
      path: '/matriculas'
      fullPath: '/mte/matriculas'
      preLoaderRoute: typeof AuthenticatedMteMatriculasRouteImport
      parentRoute: typeof AuthenticatedMteRoute
    }
    '/_authenticated/mte/importar-lista': {
      id: '/_authenticated/mte/importar-lista'
      path: '/importar-lista'
      fullPath: '/mte/importar-lista'
      preLoaderRoute: typeof AuthenticatedMteImportarListaRouteImport
      parentRoute: typeof AuthenticatedMteRoute
    }
    '/_authenticated/mte/evidencias': {
      id: '/_authenticated/mte/evidencias'
      path: '/evidencias'
      fullPath: '/mte/evidencias'
      preLoaderRoute: typeof AuthenticatedMteEvidenciasRouteImport
      parentRoute: typeof AuthenticatedMteRoute
    }
    '/_authenticated/mte/cronograma': {
      id: '/_authenticated/mte/cronograma'
      path: '/cronograma'
      fullPath: '/mte/cronograma'
      preLoaderRoute: typeof AuthenticatedMteCronogramaRouteImport
      parentRoute: typeof AuthenticatedMteRoute
    }
    '/_authenticated/mte/checklist': {
      id: '/_authenticated/mte/checklist'
      path: '/checklist'
      fullPath: '/mte/checklist'
      preLoaderRoute: typeof AuthenticatedMteChecklistRouteImport
      parentRoute: typeof AuthenticatedMteRoute
    }
    '/_authenticated/mte/beneficiarias': {
      id: '/_authenticated/mte/beneficiarias'
      path: '/beneficiarias'
      fullPath: '/mte/beneficiarias'
      preLoaderRoute: typeof AuthenticatedMteBeneficiariasRouteImport
      parentRoute: typeof AuthenticatedMteRoute
    }
    '/_authenticated/mte/ava': {
      id: '/_authenticated/mte/ava'
      path: '/ava'
      fullPath: '/mte/ava'
      preLoaderRoute: typeof AuthenticatedMteAvaRouteImport
      parentRoute: typeof AuthenticatedMteRoute
    }
    '/_authenticated/mte/aulas': {
      id: '/_authenticated/mte/aulas'
      path: '/aulas'
      fullPath: '/mte/aulas'
      preLoaderRoute: typeof AuthenticatedMteAulasRouteImport
      parentRoute: typeof AuthenticatedMteRoute
    }
    '/_authenticated/financeiro/rubricas': {
      id: '/_authenticated/financeiro/rubricas'
      path: '/rubricas'
      fullPath: '/financeiro/rubricas'
      preLoaderRoute: typeof AuthenticatedFinanceiroRubricasRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/relacoes-horas': {
      id: '/_authenticated/financeiro/relacoes-horas'
      path: '/relacoes-horas'
      fullPath: '/financeiro/relacoes-horas'
      preLoaderRoute: typeof AuthenticatedFinanceiroRelacoesHorasRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/orcamento': {
      id: '/_authenticated/financeiro/orcamento'
      path: '/orcamento'
      fullPath: '/financeiro/orcamento'
      preLoaderRoute: typeof AuthenticatedFinanceiroOrcamentoRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/fornecedores': {
      id: '/_authenticated/financeiro/fornecedores'
      path: '/fornecedores'
      fullPath: '/financeiro/fornecedores'
      preLoaderRoute: typeof AuthenticatedFinanceiroFornecedoresRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/despesas': {
      id: '/_authenticated/financeiro/despesas'
      path: '/despesas'
      fullPath: '/financeiro/despesas'
      preLoaderRoute: typeof AuthenticatedFinanceiroDespesasRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/conciliacao': {
      id: '/_authenticated/financeiro/conciliacao'
      path: '/conciliacao'
      fullPath: '/financeiro/conciliacao'
      preLoaderRoute: typeof AuthenticatedFinanceiroConciliacaoRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/configuracoes/usuarios': {
      id: '/_authenticated/configuracoes/usuarios'
      path: '/usuarios'
      fullPath: '/configuracoes/usuarios'
      preLoaderRoute: typeof AuthenticatedConfiguracoesUsuariosRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/permissoes': {
      id: '/_authenticated/configuracoes/permissoes'
      path: '/permissoes'
      fullPath: '/configuracoes/permissoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesPermissoesRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/locais': {
      id: '/_authenticated/configuracoes/locais'
      path: '/locais'
      fullPath: '/configuracoes/locais'
      preLoaderRoute: typeof AuthenticatedConfiguracoesLocaisRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/instrutor-turmas': {
      id: '/_authenticated/configuracoes/instrutor-turmas'
      path: '/instrutor-turmas'
      fullPath: '/configuracoes/instrutor-turmas'
      preLoaderRoute: typeof AuthenticatedConfiguracoesInstrutorTurmasRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/ia': {
      id: '/_authenticated/configuracoes/ia'
      path: '/ia'
      fullPath: '/configuracoes/ia'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIaRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/administrativo/qualificacao': {
      id: '/_authenticated/administrativo/qualificacao'
      path: '/qualificacao'
      fullPath: '/administrativo/qualificacao'
      preLoaderRoute: typeof AuthenticatedAdministrativoQualificacaoRouteImport
      parentRoute: typeof AuthenticatedAdministrativoRoute
    }
    '/_authenticated/administrativo/materiais': {
      id: '/_authenticated/administrativo/materiais'
      path: '/materiais'
      fullPath: '/administrativo/materiais'
      preLoaderRoute: typeof AuthenticatedAdministrativoMateriaisRouteImport
      parentRoute: typeof AuthenticatedAdministrativoRoute
    }
    '/_authenticated/administrativo/inscricoes': {
      id: '/_authenticated/administrativo/inscricoes'
      path: '/inscricoes'
      fullPath: '/administrativo/inscricoes'
      preLoaderRoute: typeof AuthenticatedAdministrativoInscricoesRouteImport
      parentRoute: typeof AuthenticatedAdministrativoRoute
    }
    '/_authenticated/administrativo/depoimentos': {
      id: '/_authenticated/administrativo/depoimentos'
      path: '/depoimentos'
      fullPath: '/administrativo/depoimentos'
      preLoaderRoute: typeof AuthenticatedAdministrativoDepoimentosRouteImport
      parentRoute: typeof AuthenticatedAdministrativoRoute
    }
    '/_authenticated/administrativo/beneficios': {
      id: '/_authenticated/administrativo/beneficios'
      path: '/beneficios'
      fullPath: '/administrativo/beneficios'
      preLoaderRoute: typeof AuthenticatedAdministrativoBeneficiosRouteImport
      parentRoute: typeof AuthenticatedAdministrativoRoute
    }
    '/_authenticated/pedagogico/turmas/$id': {
      id: '/_authenticated/pedagogico/turmas/$id'
      path: '/turmas/$id'
      fullPath: '/pedagogico/turmas/$id'
      preLoaderRoute: typeof AuthenticatedPedagogicoTurmasIdRouteImport
      parentRoute: typeof AuthenticatedPedagogicoRoute
    }
    '/_authenticated/pedagogico/turmas/$id/': {
      id: '/_authenticated/pedagogico/turmas/$id/'
      path: '/'
      fullPath: '/pedagogico/turmas/$id/'
      preLoaderRoute: typeof AuthenticatedPedagogicoTurmasIdIndexRouteImport
      parentRoute: typeof AuthenticatedPedagogicoTurmasIdRoute
    }
    '/_authenticated/pedagogico/turmas/$id/frequencia': {
      id: '/_authenticated/pedagogico/turmas/$id/frequencia'
      path: '/frequencia'
      fullPath: '/pedagogico/turmas/$id/frequencia'
      preLoaderRoute: typeof AuthenticatedPedagogicoTurmasIdFrequenciaRouteImport
      parentRoute: typeof AuthenticatedPedagogicoTurmasIdRoute
    }
    '/_authenticated/pedagogico/turmas/$id/cursistas': {
      id: '/_authenticated/pedagogico/turmas/$id/cursistas'
      path: '/cursistas'
      fullPath: '/pedagogico/turmas/$id/cursistas'
      preLoaderRoute: typeof AuthenticatedPedagogicoTurmasIdCursistasRouteImport
      parentRoute: typeof AuthenticatedPedagogicoTurmasIdRoute
    }
    '/_authenticated/pedagogico/turmas/$id/certificados': {
      id: '/_authenticated/pedagogico/turmas/$id/certificados'
      path: '/certificados'
      fullPath: '/pedagogico/turmas/$id/certificados'
      preLoaderRoute: typeof AuthenticatedPedagogicoTurmasIdCertificadosRouteImport
      parentRoute: typeof AuthenticatedPedagogicoTurmasIdRoute
    }
    '/_authenticated/pedagogico/turmas/$id/aulas': {
      id: '/_authenticated/pedagogico/turmas/$id/aulas'
      path: '/aulas'
      fullPath: '/pedagogico/turmas/$id/aulas'
      preLoaderRoute: typeof AuthenticatedPedagogicoTurmasIdAulasRouteImport
      parentRoute: typeof AuthenticatedPedagogicoTurmasIdRoute
    }
  }
}

interface AuthenticatedAdministrativoRouteChildren {
  AuthenticatedAdministrativoBeneficiosRoute: typeof AuthenticatedAdministrativoBeneficiosRoute
  AuthenticatedAdministrativoDepoimentosRoute: typeof AuthenticatedAdministrativoDepoimentosRoute
  AuthenticatedAdministrativoInscricoesRoute: typeof AuthenticatedAdministrativoInscricoesRoute
  AuthenticatedAdministrativoMateriaisRoute: typeof AuthenticatedAdministrativoMateriaisRoute
  AuthenticatedAdministrativoQualificacaoRoute: typeof AuthenticatedAdministrativoQualificacaoRoute
  AuthenticatedAdministrativoIndexRoute: typeof AuthenticatedAdministrativoIndexRoute
}

const AuthenticatedAdministrativoRouteChildren: AuthenticatedAdministrativoRouteChildren =
  {
    AuthenticatedAdministrativoBeneficiosRoute:
      AuthenticatedAdministrativoBeneficiosRoute,
    AuthenticatedAdministrativoDepoimentosRoute:
      AuthenticatedAdministrativoDepoimentosRoute,
    AuthenticatedAdministrativoInscricoesRoute:
      AuthenticatedAdministrativoInscricoesRoute,
    AuthenticatedAdministrativoMateriaisRoute:
      AuthenticatedAdministrativoMateriaisRoute,
    AuthenticatedAdministrativoQualificacaoRoute:
      AuthenticatedAdministrativoQualificacaoRoute,
    AuthenticatedAdministrativoIndexRoute:
      AuthenticatedAdministrativoIndexRoute,
  }

const AuthenticatedAdministrativoRouteWithChildren =
  AuthenticatedAdministrativoRoute._addFileChildren(
    AuthenticatedAdministrativoRouteChildren,
  )

interface AuthenticatedConfiguracoesRouteChildren {
  AuthenticatedConfiguracoesIaRoute: typeof AuthenticatedConfiguracoesIaRoute
  AuthenticatedConfiguracoesInstrutorTurmasRoute: typeof AuthenticatedConfiguracoesInstrutorTurmasRoute
  AuthenticatedConfiguracoesLocaisRoute: typeof AuthenticatedConfiguracoesLocaisRoute
  AuthenticatedConfiguracoesPermissoesRoute: typeof AuthenticatedConfiguracoesPermissoesRoute
  AuthenticatedConfiguracoesUsuariosRoute: typeof AuthenticatedConfiguracoesUsuariosRoute
  AuthenticatedConfiguracoesIndexRoute: typeof AuthenticatedConfiguracoesIndexRoute
}

const AuthenticatedConfiguracoesRouteChildren: AuthenticatedConfiguracoesRouteChildren =
  {
    AuthenticatedConfiguracoesIaRoute: AuthenticatedConfiguracoesIaRoute,
    AuthenticatedConfiguracoesInstrutorTurmasRoute:
      AuthenticatedConfiguracoesInstrutorTurmasRoute,
    AuthenticatedConfiguracoesLocaisRoute:
      AuthenticatedConfiguracoesLocaisRoute,
    AuthenticatedConfiguracoesPermissoesRoute:
      AuthenticatedConfiguracoesPermissoesRoute,
    AuthenticatedConfiguracoesUsuariosRoute:
      AuthenticatedConfiguracoesUsuariosRoute,
    AuthenticatedConfiguracoesIndexRoute: AuthenticatedConfiguracoesIndexRoute,
  }

const AuthenticatedConfiguracoesRouteWithChildren =
  AuthenticatedConfiguracoesRoute._addFileChildren(
    AuthenticatedConfiguracoesRouteChildren,
  )

interface AuthenticatedFinanceiroRouteChildren {
  AuthenticatedFinanceiroConciliacaoRoute: typeof AuthenticatedFinanceiroConciliacaoRoute
  AuthenticatedFinanceiroDespesasRoute: typeof AuthenticatedFinanceiroDespesasRoute
  AuthenticatedFinanceiroFornecedoresRoute: typeof AuthenticatedFinanceiroFornecedoresRoute
  AuthenticatedFinanceiroOrcamentoRoute: typeof AuthenticatedFinanceiroOrcamentoRoute
  AuthenticatedFinanceiroRelacoesHorasRoute: typeof AuthenticatedFinanceiroRelacoesHorasRoute
  AuthenticatedFinanceiroRubricasRoute: typeof AuthenticatedFinanceiroRubricasRoute
  AuthenticatedFinanceiroIndexRoute: typeof AuthenticatedFinanceiroIndexRoute
}

const AuthenticatedFinanceiroRouteChildren: AuthenticatedFinanceiroRouteChildren =
  {
    AuthenticatedFinanceiroConciliacaoRoute:
      AuthenticatedFinanceiroConciliacaoRoute,
    AuthenticatedFinanceiroDespesasRoute: AuthenticatedFinanceiroDespesasRoute,
    AuthenticatedFinanceiroFornecedoresRoute:
      AuthenticatedFinanceiroFornecedoresRoute,
    AuthenticatedFinanceiroOrcamentoRoute:
      AuthenticatedFinanceiroOrcamentoRoute,
    AuthenticatedFinanceiroRelacoesHorasRoute:
      AuthenticatedFinanceiroRelacoesHorasRoute,
    AuthenticatedFinanceiroRubricasRoute: AuthenticatedFinanceiroRubricasRoute,
    AuthenticatedFinanceiroIndexRoute: AuthenticatedFinanceiroIndexRoute,
  }

const AuthenticatedFinanceiroRouteWithChildren =
  AuthenticatedFinanceiroRoute._addFileChildren(
    AuthenticatedFinanceiroRouteChildren,
  )

interface AuthenticatedMteRouteChildren {
  AuthenticatedMteAulasRoute: typeof AuthenticatedMteAulasRoute
  AuthenticatedMteAvaRoute: typeof AuthenticatedMteAvaRoute
  AuthenticatedMteBeneficiariasRoute: typeof AuthenticatedMteBeneficiariasRoute
  AuthenticatedMteChecklistRoute: typeof AuthenticatedMteChecklistRoute
  AuthenticatedMteCronogramaRoute: typeof AuthenticatedMteCronogramaRoute
  AuthenticatedMteEvidenciasRoute: typeof AuthenticatedMteEvidenciasRoute
  AuthenticatedMteImportarListaRoute: typeof AuthenticatedMteImportarListaRoute
  AuthenticatedMteMatriculasRoute: typeof AuthenticatedMteMatriculasRoute
  AuthenticatedMtePresencasRoute: typeof AuthenticatedMtePresencasRoute
  AuthenticatedMteTurmasRoute: typeof AuthenticatedMteTurmasRoute
  AuthenticatedMteIndexRoute: typeof AuthenticatedMteIndexRoute
}

const AuthenticatedMteRouteChildren: AuthenticatedMteRouteChildren = {
  AuthenticatedMteAulasRoute: AuthenticatedMteAulasRoute,
  AuthenticatedMteAvaRoute: AuthenticatedMteAvaRoute,
  AuthenticatedMteBeneficiariasRoute: AuthenticatedMteBeneficiariasRoute,
  AuthenticatedMteChecklistRoute: AuthenticatedMteChecklistRoute,
  AuthenticatedMteCronogramaRoute: AuthenticatedMteCronogramaRoute,
  AuthenticatedMteEvidenciasRoute: AuthenticatedMteEvidenciasRoute,
  AuthenticatedMteImportarListaRoute: AuthenticatedMteImportarListaRoute,
  AuthenticatedMteMatriculasRoute: AuthenticatedMteMatriculasRoute,
  AuthenticatedMtePresencasRoute: AuthenticatedMtePresencasRoute,
  AuthenticatedMteTurmasRoute: AuthenticatedMteTurmasRoute,
  AuthenticatedMteIndexRoute: AuthenticatedMteIndexRoute,
}

const AuthenticatedMteRouteWithChildren =
  AuthenticatedMteRoute._addFileChildren(AuthenticatedMteRouteChildren)

interface AuthenticatedPedagogicoTurmasIdRouteChildren {
  AuthenticatedPedagogicoTurmasIdAulasRoute: typeof AuthenticatedPedagogicoTurmasIdAulasRoute
  AuthenticatedPedagogicoTurmasIdCertificadosRoute: typeof AuthenticatedPedagogicoTurmasIdCertificadosRoute
  AuthenticatedPedagogicoTurmasIdCursistasRoute: typeof AuthenticatedPedagogicoTurmasIdCursistasRoute
  AuthenticatedPedagogicoTurmasIdFrequenciaRoute: typeof AuthenticatedPedagogicoTurmasIdFrequenciaRoute
  AuthenticatedPedagogicoTurmasIdIndexRoute: typeof AuthenticatedPedagogicoTurmasIdIndexRoute
}

const AuthenticatedPedagogicoTurmasIdRouteChildren: AuthenticatedPedagogicoTurmasIdRouteChildren =
  {
    AuthenticatedPedagogicoTurmasIdAulasRoute:
      AuthenticatedPedagogicoTurmasIdAulasRoute,
    AuthenticatedPedagogicoTurmasIdCertificadosRoute:
      AuthenticatedPedagogicoTurmasIdCertificadosRoute,
    AuthenticatedPedagogicoTurmasIdCursistasRoute:
      AuthenticatedPedagogicoTurmasIdCursistasRoute,
    AuthenticatedPedagogicoTurmasIdFrequenciaRoute:
      AuthenticatedPedagogicoTurmasIdFrequenciaRoute,
    AuthenticatedPedagogicoTurmasIdIndexRoute:
      AuthenticatedPedagogicoTurmasIdIndexRoute,
  }

const AuthenticatedPedagogicoTurmasIdRouteWithChildren =
  AuthenticatedPedagogicoTurmasIdRoute._addFileChildren(
    AuthenticatedPedagogicoTurmasIdRouteChildren,
  )

interface AuthenticatedPedagogicoRouteChildren {
  AuthenticatedPedagogicoIndexRoute: typeof AuthenticatedPedagogicoIndexRoute
  AuthenticatedPedagogicoTurmasIdRoute: typeof AuthenticatedPedagogicoTurmasIdRouteWithChildren
}

const AuthenticatedPedagogicoRouteChildren: AuthenticatedPedagogicoRouteChildren =
  {
    AuthenticatedPedagogicoIndexRoute: AuthenticatedPedagogicoIndexRoute,
    AuthenticatedPedagogicoTurmasIdRoute:
      AuthenticatedPedagogicoTurmasIdRouteWithChildren,
  }

const AuthenticatedPedagogicoRouteWithChildren =
  AuthenticatedPedagogicoRoute._addFileChildren(
    AuthenticatedPedagogicoRouteChildren,
  )

interface AuthenticatedRelatoriosRouteChildren {
  AuthenticatedRelatoriosFrequenciaRoute: typeof AuthenticatedRelatoriosFrequenciaRoute
  AuthenticatedRelatoriosIndicadoresRoute: typeof AuthenticatedRelatoriosIndicadoresRoute
  AuthenticatedRelatoriosMetasRoute: typeof AuthenticatedRelatoriosMetasRoute
  AuthenticatedRelatoriosMteRoute: typeof AuthenticatedRelatoriosMteRoute
  AuthenticatedRelatoriosOrcamentarioRoute: typeof AuthenticatedRelatoriosOrcamentarioRoute
  AuthenticatedRelatoriosParcialObjetoRoute: typeof AuthenticatedRelatoriosParcialObjetoRoute
  AuthenticatedRelatoriosPedagogicoRoute: typeof AuthenticatedRelatoriosPedagogicoRoute
  AuthenticatedRelatoriosIndexRoute: typeof AuthenticatedRelatoriosIndexRoute
}

const AuthenticatedRelatoriosRouteChildren: AuthenticatedRelatoriosRouteChildren =
  {
    AuthenticatedRelatoriosFrequenciaRoute:
      AuthenticatedRelatoriosFrequenciaRoute,
    AuthenticatedRelatoriosIndicadoresRoute:
      AuthenticatedRelatoriosIndicadoresRoute,
    AuthenticatedRelatoriosMetasRoute: AuthenticatedRelatoriosMetasRoute,
    AuthenticatedRelatoriosMteRoute: AuthenticatedRelatoriosMteRoute,
    AuthenticatedRelatoriosOrcamentarioRoute:
      AuthenticatedRelatoriosOrcamentarioRoute,
    AuthenticatedRelatoriosParcialObjetoRoute:
      AuthenticatedRelatoriosParcialObjetoRoute,
    AuthenticatedRelatoriosPedagogicoRoute:
      AuthenticatedRelatoriosPedagogicoRoute,
    AuthenticatedRelatoriosIndexRoute: AuthenticatedRelatoriosIndexRoute,
  }

const AuthenticatedRelatoriosRouteWithChildren =
  AuthenticatedRelatoriosRoute._addFileChildren(
    AuthenticatedRelatoriosRouteChildren,
  )

interface AuthenticatedWhatsappRouteChildren {
  AuthenticatedWhatsappImportacaoIdRoute: typeof AuthenticatedWhatsappImportacaoIdRoute
  AuthenticatedWhatsappIndexRoute: typeof AuthenticatedWhatsappIndexRoute
}

const AuthenticatedWhatsappRouteChildren: AuthenticatedWhatsappRouteChildren = {
  AuthenticatedWhatsappImportacaoIdRoute:
    AuthenticatedWhatsappImportacaoIdRoute,
  AuthenticatedWhatsappIndexRoute: AuthenticatedWhatsappIndexRoute,
}

const AuthenticatedWhatsappRouteWithChildren =
  AuthenticatedWhatsappRoute._addFileChildren(
    AuthenticatedWhatsappRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministrativoRoute: typeof AuthenticatedAdministrativoRouteWithChildren
  AuthenticatedAjudaRoute: typeof AuthenticatedAjudaRoute
  AuthenticatedBaseConhecimentoRoute: typeof AuthenticatedBaseConhecimentoRoute
  AuthenticatedCaptacaoRoute: typeof AuthenticatedCaptacaoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRouteWithChildren
  AuthenticatedDriveRoute: typeof AuthenticatedDriveRoute
  AuthenticatedEtapasRoute: typeof AuthenticatedEtapasRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRouteWithChildren
  AuthenticatedMinhasDemandasRoute: typeof AuthenticatedMinhasDemandasRoute
  AuthenticatedMteRoute: typeof AuthenticatedMteRouteWithChildren
  AuthenticatedPedagogicoRoute: typeof AuthenticatedPedagogicoRouteWithChildren
  AuthenticatedPendenciasRoute: typeof AuthenticatedPendenciasRoute
  AuthenticatedRelacaoHorasRoute: typeof AuthenticatedRelacaoHorasRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRouteWithChildren
  AuthenticatedTrocarSenhaRoute: typeof AuthenticatedTrocarSenhaRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministrativoRoute:
    AuthenticatedAdministrativoRouteWithChildren,
  AuthenticatedAjudaRoute: AuthenticatedAjudaRoute,
  AuthenticatedBaseConhecimentoRoute: AuthenticatedBaseConhecimentoRoute,
  AuthenticatedCaptacaoRoute: AuthenticatedCaptacaoRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRouteWithChildren,
  AuthenticatedDriveRoute: AuthenticatedDriveRoute,
  AuthenticatedEtapasRoute: AuthenticatedEtapasRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRouteWithChildren,
  AuthenticatedMinhasDemandasRoute: AuthenticatedMinhasDemandasRoute,
  AuthenticatedMteRoute: AuthenticatedMteRouteWithChildren,
  AuthenticatedPedagogicoRoute: AuthenticatedPedagogicoRouteWithChildren,
  AuthenticatedPendenciasRoute: AuthenticatedPendenciasRoute,
  AuthenticatedRelacaoHorasRoute: AuthenticatedRelacaoHorasRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRouteWithChildren,
  AuthenticatedTrocarSenhaRoute: AuthenticatedTrocarSenhaRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ImprimirInscricaoRoute: ImprimirInscricaoRoute,
  InscricaoRoute: InscricaoRoute,
  MulheresConectadasRoute: MulheresConectadasRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
